name: Airtable Order Checker

on:
  schedule:
    # MF/FAIRE Checks (Tues & Thurs at 2:30 PM & 4:30 PM MT = 20:30 & 22:30 UTC)
    - cron: "30 20 * * 2,4"
    - cron: "30 22 * * 2,4"
    # DNA Check (Tuesdays at 12:00 PM MT = 18:00 UTC)
    - cron: "0 18 * * 2"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Airtable Check
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        run: python main.py
